apiVersion: v1
kind: Service
metadata:
  name: cloud-cost-optimizer-backend
  namespace: cloud-cost-optimizer
  labels:
    app: cloud-cost-optimizer
    tier: backend
spec:
  selector:
    app: cloud-cost-optimizer
    tier: backend
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  type: ClusterIP
