apiVersion: v1
kind: Service
metadata:
  name: cloud-cost-optimizer-backend
  namespace: cloud-cost-optimizer
spec:
  selector:
    app: cloud-cost-optimizer-backend
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP
