apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-v2
  namespace: cloud-cost-optimizer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc-v2
  resources:
    requests:
      storage: 10Gi
