apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: cloud-cost-optimizer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 5Gi
