apiVersion: v1
kind: Service
metadata:
  name: cloud-cost-optimizer-frontend
  namespace: cloud-cost-optimizer
  labels:
    app: cloud-cost-optimizer
    tier: frontend
spec:
  selector:
    app: cloud-cost-optimizer
    tier: frontend
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  type: LoadBalancer
