apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-cost-optimizer-frontend
  namespace: cloud-cost-optimizer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud-cost-optimizer-frontend
  template:
    metadata:
      labels:
        app: cloud-cost-optimizer-frontend
    spec:
      containers:
      - name: frontend
        image: 637423222780.dkr.ecr.us-east-1.amazonaws.com/cloud-cost-optimizer-frontend
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "/api"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 15
