apiVersion: v1
kind: Service
metadata:
  name: cloud-cost-optimizer-frontend
  namespace: cloud-cost-optimizer
spec:
  selector:
    app: cloud-cost-optimizer-frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
