apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-cost-optimizer-ingress
  namespace: cloud-cost-optimizer
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /(.*)
        pathType: Prefix
        backend:
          service:
            name: cloud-cost-optimizer-frontend
            port:
              number: 80
      - path: /api/(.*)
        pathType: Prefix
        backend:
          service:
            name: cloud-cost-optimizer-backend
            port:
              number: 80
