apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloud-cost-optimizer
resources:
  - configmap.yaml
  - secrets.yaml
  - storage-class-ebs.yaml
  - postgres-schema-configmap.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - postgres-init-job.yaml
  - terraform-state-pvc.yaml
  - database-pvc.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
