apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloud-cost-optimizer
resources:
  - configmap.yaml
  - secrets.yaml
  - storage-class-ebs-v2.yaml
  - postgres-schema-configmap.yaml
  - postgres-statefulset-v2.yaml
  - postgres-service.yaml
  - postgres-init-job.yaml
  - terraform-state-v2-pvc.yaml
  - database-v2-pvc.yaml
  - backend-deployment-v2.yaml
  - backend-service.yaml
  - frontend-deployment-v2.yaml
  - frontend-service.yaml
  - ingress.yaml
