apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- service-account.yaml
- rbac.yaml
- configmap.yaml
- secrets.yaml
- storage-class.yaml
<<<<<<< HEAD
- terraform-state-pv.yaml
- database-pv.yaml
=======
- persistent-volumes.yaml
>>>>>>> 30402d48bafbc7664fafa92efffb15ad12e4e8fd
- persistent-volume-claims.yaml
- backend-deployment.yaml
- backend-service.yaml
- frontend-deployment.yaml
- frontend-service.yaml
- horizontal-pod-autoscaler.yaml
- ingress.yaml
