apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- storage-class-ebs.yaml
- terraform-state-new-pvc.yaml
- database-new-pvc.yaml
- backend-deployment-updated.yaml

namespace: cloud-cost-optimizer
