apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- service-account.yaml
- rbac.yaml
- storage-class.yaml
- storage-class-ebs.yaml
- terraform-state-new-pvc.yaml
- database-new-pvc.yaml
- backend-deployment.yaml
- backend-service.yaml
- frontend-deployment.yaml
- frontend-service.yaml
- ingress.yaml
- configmap.yaml
- secrets.yaml
- horizontal-pod-autoscaler.yaml

namespace: cloud-cost-optimizer
