apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terraform-state-pvc
  namespace: cloud-cost-optimizer
  labels:
    app: cloud-cost-optimizer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: cloud-cost-optimizer
  labels:
    app: cloud-cost-optimizer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi
