apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-v2
  namespace: cloud-cost-optimizer
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres-v2
  template:
    metadata:
      labels:
        app: postgres-v2
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: cloud-cost-optimizer-secrets
              key: postgres_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloud-cost-optimizer-secrets
              key: postgres_password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: cloud-cost-optimizer-config
              key: postgres_db
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: ebs-sc-v2
      resources:
        requests:
          storage: 10Gi
