apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloud-cost-optimizer-role
  namespace: cloud-cost-optimizer
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloud-cost-optimizer-rolebinding
  namespace: cloud-cost-optimizer
subjects:
- kind: ServiceAccount
  name: cloud-cost-optimizer-sa
  namespace: cloud-cost-optimizer
roleRef:
  kind: Role
  name: cloud-cost-optimizer-role
  apiGroup: rbac.authorization.k8s.io
