apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terraform-state-new
  namespace: cloud-cost-optimizer
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 5Gi
