apiVersion: v1
kind: PersistentVolume
metadata:
  name: terraform-state-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data/terraform-state
    type: DirectoryOrCreate
