
type: github_actions
provider: github
name: CloudCrawl CI/CD Pipeline
description: GitHub Actions workflow for building, testing, and deploying CloudCrawl

stages:
  - name: build
    description: Build the application
    steps:
      - name: Checkout code
        action: actions/checkout@v2
      - name: Set up Node.js
        action: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: |
          npm ci
      - name: Build
        run: |
          npm run build

  - name: test
    description: Run tests
    steps:
      - name: Run unit tests
        run: |
          npm test
      - name: Run integration tests
        run: |
          npm run test:integration

  - name: deploy
    description: Deploy to environment
    steps:
      - name: Set up kubectl
        action: azure/setup-kubectl@v1
      - name: Set up Helm
        action: azure/setup-helm@v1
      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install cloudcrawl ./charts/cloudcrawl --namespace ${{ env.NAMESPACE }} --set image.tag=${{ env.VERSION }}
