apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# No images block needed since we're using fully qualified ECR image names directly in the base manifests

# Using create instead of merge since the ConfigMap already exists in base
configMapGenerator:
- name: cloud-cost-optimizer-config-overlay
  behavior: create
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=info
