apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# Using replace behavior for the ConfigMap to ensure it overrides the base one
configMapGenerator:
- name: cloud-cost-optimizer-config
  behavior: replace
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=info
