apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# Using create instead of replace for the ConfigMap
configMapGenerator:
- name: cloud-cost-optimizer-config
  behavior: merge
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=info
