apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: cloud-cost-optimizer-backend:latest
  newName: your-registry/cloud-cost-optimizer-backend
  newTag: latest
- name: cloud-cost-optimizer-frontend:latest
  newName: your-registry/cloud-cost-optimizer-frontend
  newTag: latest

# Using create instead of merge since the ConfigMap already exists in base
configMapGenerator:
- name: cloud-cost-optimizer-config-overlay
  behavior: create
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=info
