apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloud-cost-optimizer
resources:
  - ../../base
images:
  - name: ${BACKEND_IMAGE}
    newName: your-registry/cloud-cost-optimizer-backend
    newTag: latest
  - name: ${FRONTEND_IMAGE}
    newName: your-registry/cloud-cost-optimizer-frontend
    newTag: latest
