apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# Using create instead of merge for the production-specific ConfigMap
configMapGenerator:
- name: cloud-cost-optimizer-config
  behavior: replace
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=info
