apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# Using configMapGenerator with create behavior instead of merge
configMapGenerator:
- name: cloud-cost-optimizer-config
  behavior: create
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=info

# Explicitly set the backend image to prevent variable substitution
images:
- name: ${BACKEND_IMAGE}
  newName: 637423222780.dkr.ecr.us-east-1.amazonaws.com/cloud-cost-optimizer-backend
  newTag: latest
