apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# Using configMapGenerator with create behavior instead of merge
configMapGenerator:
- name: cloud-cost-optimizer-config
  behavior: create
  literals:
  - ENVIRONMENT=production
  - LOG_LEVEL=info
