name: Terraform AWS Resources

on:
  push:
    branches: [ main ]
    paths:
      - 'k8s-manifests/terraform/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'k8s-manifests/terraform/**'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: PrimusAllCluster

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.0

    - name: Terraform Init
      run: |
        cd k8s-manifests/terraform
        terraform init

    - name: Terraform Plan
      run: |
        cd k8s-manifests/terraform
        terraform plan -var="cluster_name=${{ env.EKS_CLUSTER_NAME }}" -var="region=${{ env.AWS_REGION }}" -out=tfplan

    - name: Terraform Apply
      if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
      run: |
        cd k8s-manifests/terraform
        terraform apply -auto-approve tfplan

        ROLE_ARN=$(terraform output -raw cost_optimizer_role_arn )
        echo "COST_OPTIMIZER_ROLE_ARN=$ROLE_ARN" >> $GITHUB_ENV

        echo "Backend ECR: $(terraform output -raw backend_repository_url)"
        echo "Frontend ECR: $(terraform output -raw frontend_repository_url)"
